### ISSUE TITLE
Can't scan XPUB QR code when adding an airgapped key

### ISSUE THREAD

**Issue by hugohn** [nunchuk-io/nunchuk-desktop#42]
Looks like a regression. Reproducible on Jade and SeedSigner.

**Comment by Funman2** [comment]
maybe this is related: https://github.com/nunchuk-io/nunchuk-desktop/issues/41#issuecomment-1584212678

**Comment by hugohn** [comment]
Fixed in 1.9.20: https://github.com/nunchuk-io/nunchuk-desktop/releases/tag/1.9.20

**Comment by cwiggs** [comment]
The issue still exists for me on 1.9.20 on MacOS.  To elaborate on what happens:

* Open nunchuk in guest mode.
* Click the + symbol to add a key.
* Add hardware key
* Add an air-gapped key
* Click the QR code button and scan the nunchuk xpub QR code on the seedsigner display.
* After nunchuk seems to scan the QR code nothing is input into the fields on the left (Xpub, BIP32 Path, Master Key Fingerprint).  The Add key button is still un-clickable.

**Comment by hugohn** [comment]
Hey @cwiggs , we haven’t released the Mac version yet. Only Linux/Windows. (Coming soon).

**Comment by Funman2** [comment]
I can confirm iit works in latest windows version now...but strange enough only in second attempt after naming the key....

**Comment by hugohn** [comment]
@cwiggs @Funman2 the Mac version is out now (also updated Linux/Windows versions)
https://github.com/nunchuk-io/nunchuk-desktop/releases/tag/1.9.20

**Comment by cwiggs** [comment]
Works on Macos now.  Thanks!
